version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 7.0.3
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.1.1
    - 7.1.2
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.2
    - 1.4.3
    - 1.4.5
    - 1.4.7
    - 1.4.9
  - dependency-name: ccxt
    versions:
    - 1.40.96
    - 1.41.34
    - 1.41.70
    - 1.41.89
    - 1.42.18
    - 1.42.47
    - 1.42.66
    - 1.43.26
    - 1.43.88
    - 1.45.38
    - 1.46.38
    - 1.47.47
    - 1.48.22
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: joblib
    versions:
    - 1.0.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.7.9.pre.slim.pre.stretch
